Messages:
  noPermission: '&b[&cComidas&b] &eNo tienes permiso para hacer esto.'
  notEnoughArgs: '&b[&cComida&b] &eNo has especificado suficientes argumentos.'
  foodAdded: "&b[&cComida&b] &eSe ha añadido valor nutricional a este objeto."
  foodArguments: "&b[&cComida&b] &eEl uso es /greatdevourer food <Valor> <Saturación> [Siempre] [Tiempo]."
  effectAdded: "&b[&cComida&b] &eSe ha añadido un efecto a este objeto."
  effectArguments: "&b[&cComida&b] &eEl uso es /greatdevourer effect <Efecto> <Duración> <Nivel>."
  soundAdded: "&b[&cComida&b] &eSe ha añadido un sonido a este objeto."
  soundArguments: "&b[&cComida&b] &eEl uso es /greatdevourer sound <Sonido> [Volumen] [Tono]."
  get:
    - "&b&m================================================"
    - "&bValor nutricional: &e%value%"
    - "&bSaturación: &e%saturation%"
    - "&bSe puede comer siempre: &e%always%"
    - "&bTiempo para consumir: &e%time%s"
    - "&bEfectos:"
    - "     - %effect_line%"
    - "&bSonido: %sound%"
    - "&b&m================================================"
  effectLine: "&e%effect% %duration%s %level%"
  noEffects: "&eEste objeto no tiene efectos."
  noSound: "&eEste objeto no tiene sonido."
  help:
    - "&b/gd &eMuestra esta página."
    - "&b/gd food <Valor> <Saturación> [Siempre] [Tiempo] &eAñade valor nutricional a un objeto."
    - "&b/gd effect <Efecto> <Duración> <Nivel> &eAñade un efecto al comer el objeto."
    - "&b/gd sound <Sonido> [Volumen] [Tono] &eAñade un sonido al comer el objeto."
    - "&b/gd get &eMuestra los valores nutricionales del objeto, si los tiene."
    - "&b"
    - "&eLeyenda: &b<> &eObligatorio  &b[] &eOpcional"

Config:
  baseAlwaysValue: false
  baseTimeValue: 1.6
  baseVolumeValue: 1
  basePitchValue: 1

Items:
  foodLine: "&7Valor nutricional: &d%value%"
  saturationLine: "&7Saturación: &d%saturation%"
  alwaysLine: "&7Se puede comer siempre: &d%always%"
  timeLine: "&7Tiempo para consumir: &d%time%"